const badges = {
    'APACHE': "[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)",
    'BOOST': "[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)",
    'CC0': "[![License: CC0-1.0](https://licensebuttons.net/l/zero/1.0/80x15.png)](http://creativecommons.org/publicdomain/zero/1.0/)",
    'ISC': "[![License: ISC](https://img.shields.io/badge/License-ISC-blue.svg)](https://opensource.org/licenses/ISC)",
    'MIT': "[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)",
    'ZLIB': "[![License: Zlib](https://img.shields.io/badge/License-Zlib-lightgrey.svg)](https://opensource.org/licenses/Zlib)"
}

const links = {
	'APACHE': "https://www.apache.org/licenses/LICENSE-2.0.txt",
	'BOOST': "https://www.boost.org/users/license.html",
	'CC0': "https://creativecommons.org/publicdomain/zero/1.0/",
	'ISC': "https://opensource.org/licenses/ISC",
	'MIT': "https://opensource.org/licenses/MIT",
	'ZLIB': "https://www.zlib.net/zlib_license.html"
}

const sections = {
	'APACHE': "Please refer to Apache 2.0 link for license information.",
	'BOOST': "Boost Software License - Version 1.0 - August 17th, 2003\n" +
		"\n" +
		"Permission is hereby granted, free of charge, to any person or organization\n" +
		"obtaining a copy of the software and accompanying documentation covered by\n" +
		"this license (the \"Software\") to use, reproduce, display, distribute,\n" +
		"execute, and transmit the Software, and to prepare derivative works of the\n" +
		"Software, and to permit third-parties to whom the Software is furnished to\n" +
		"do so, all subject to the following:\n" +
		"\n" +
		"The copyright notices in the Software and this entire statement, including\n" +
		"the above license grant, this restriction and the following disclaimer,\n" +
		"must be included in all copies of the Software, in whole or in part, and\n" +
		"all derivative works of the Software, unless such copies or derivative\n" +
		"works are solely in the form of machine-executable object code generated by\n" +
		"a source language processor.\n" +
		"\n" +
		"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n" +
		"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n" +
		"FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\n" +
		"SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\n" +
		"FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\n" +
		"ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n" +
		"DEALINGS IN THE SOFTWARE.",
	'CC0': " The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.\n" +
		"\n" +
		"You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. Please refer to link for more information.",
	'ISC': " Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.\n" +
"\n" +
"THE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. ",
	'MIT': "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n" +
"\n" +
"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n" +
"\n" +
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
	'ZLIB': "zlib.h -- interface of the 'zlib' general purpose compression library\n" +
"  version 1.2.13, October 13th, 2022\n" +
"\n" +
"  Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler\n" +
"\n" +
"  This software is provided 'as-is', without any express or implied\n" +
"  warranty.  In no event will the authors be held liable for any damages\n" +
"  arising from the use of this software.\n" +
"\n" +
"  Permission is granted to anyone to use this software for any purpose,\n" +
"  including commercial applications, and to alter it and redistribute it\n" +
"  freely, subject to the following restrictions:\n" +
"\n" +
"  1. The origin of this software must not be misrepresented; you must not\n" +
"     claim that you wrote the original software. If you use this software\n" +
"     in a product, an acknowledgment in the product documentation would be\n" +
"     appreciated but is not required.\n" +
"  2. Altered source versions must be plainly marked as such, and must not be\n" +
"     misrepresented as being the original software.\n" +
"  3. This notice may not be removed or altered from any source distribution.\n" +
"\n" +
"  Jean-loup Gailly        Mark Adler\n" +
"  jloup@gzip.org          madler@alumni.caltech.edu"
}

module.exports = { badges, links, sections };
